name: Hotfix

on:
  push:
    branches:
      - main

jobs:
  hotfix:
    # commit message가 [hotfix]로 시작하면 실행
    if: startsWith(github.event.head_commit.message, '[hotfix]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .env
        run: |
          echo "${{ secrets.DOT_ENV }}" > .env

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          # build 안 모든 파일을 EC2로 전송
          source: build/*
          target: /home/ubuntu/dp-web-app/public/
          strip_components: 1